# Generated by Django 2.2.16 on 2021-12-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='text_comment',
        ),
    ]
