# Generated by Django 2.2.16 on 2021-12-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20211206_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='pub_date',
        ),
    ]
