# Generated by Django 2.2.16 on 2021-12-09 19:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20211209_2156'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='subscribe_to_yourself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(author=django.db.models.expressions.F('user')), name='subscribe_to_yourself'),
        ),
    ]
