# Generated by Django 2.2.16 on 2021-12-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20211209_2230'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='subscribe_to_yourself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=True, name='subscribe_to_yourself'),
        ),
    ]
