# Generated by Django 2.2.16 on 2021-12-09 20:13

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20211209_2241'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='subscribe_to_yourself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='subscribe_to_yourself'),
        ),
    ]
