# Generated by Django 2.2.16 on 2021-12-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20211209_2314'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='subscribe_to_yourself',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_1',
            new_name='user',
        ),
    ]
