AUTHOR = 'auth'
GROUP_TITLE = 'Тестовая группа'
GROUP_SLUG = 'test_slug'
GROUP_DESCRIPTION = 'Тестовое описание'
POST_TEXT = 'Тестовая запись'

INDEX_URL = '/'
ABOUT_AUTHOR_URL = '/about/author/'
ABOUT_TECH_URL = '/about/tech/'
GROUP_URL = '/group/' + GROUP_SLUG + '/'
PROFILE_URL = '/profile/' + AUTHOR + '/'
CREATE_URL = '/create/'
POST_URL = '/posts/'
EDIT_URL = '/edit/'
